name: Deploy to Railway

# on:
#   push:
#     branches: [main]
on:
  workflow_call:
    secrets:
      RAILWAY_TOKEN:
        required: true

# permissions:
#   contents: write
#   id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: b3cb242e-dbf0-43e1-be00-13a66cbeb30b
      # RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}
