name: Main CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  deploy_front:
    needs: tests
    if: success()
    uses: ./.github/workflows/deploy-pages.yml

  deploy_back:
    needs: deploy_front
    if: success()
    uses: ./.github/workflows/deploy-railway.yml
    secrets:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  # deploy_back:
  #   needs: deploy_front
  #   if: success()
  #   runs-on: ubuntu-latest
  #   container: ghcr.io/railwayapp/cli:latest
  #   env:
  #     SVC_ID: b3cb242e-dbf0-43e1-be00-13a66cbeb30b
  #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: railway up --service=${{ env.SVC_ID }}
